In [19]:
import pandas as pd

customers = pd.read_csv("../data/clean/customers_clean.csv")
accounts = pd.read_csv("../data/clean/accounts_clean.csv")
loans = pd.read_csv("../data/clean/loans_clean.csv")
transactions = pd.read_csv("../data/clean/transactions_clean.csv")
branches = pd.read_csv("../data/clean/branches_clean.csv")

In [20]:
validation_summary = pd.DataFrame({
    "Dataset": [ "customers","accounts","loans", "transactions","branches"],
    "Missing Values": [
        customers.isnull().sum().sum(),
        accounts.isnull().sum().sum(),
        loans.isnull().sum().sum(),
        transactions.isnull().sum().sum(),
        branches.isnull().sum().sum()
    ],
    "Duplicate Rows": [
        customers.duplicated().sum(),
        accounts.duplicated().sum(),
        loans.duplicated().sum(),
        transactions.duplicated().sum(),
        branches.duplicated().sum()
    ]
})

validation_summary

        Dataset  Missing Values  Duplicate Rows
0     customers               0               0
1      accounts               0               0
2         loans               0               0
3  transactions               0               0
4      branches               0               0

In [21]:
def validate_dataset(df, name, primary_key):
    print("=" * 60)
    print(f"{name.upper()} DATASET")
    print("=" * 60)

    print(f"Rows: {df.shape[0]}")
    print(f"Columns: {df.shape[1]}")

    print("\nMissing Values")
    print(df.isnull().sum())

    print("\nDuplicate Rows")
    print(df.duplicated().sum())

    print("\nDuplicate Primary Keys")
    print(df[primary_key].duplicated().sum())

    print("\nData Types")
    print(df.dtypes)

    print("\n")
    
validate_dataset(customers, "Customers", "customer_id")
validate_dataset(accounts, "Accounts", "account_id")
validate_dataset(loans, "Loans", "loan_id")
validate_dataset(transactions, "Transactions", "transaction_id")
validate_dataset(branches, "Branches", "branch_id")

============================================================
CUSTOMERS DATASET
============================================================
Rows: 75000
Columns: 13

Missing Values
customer_id         0
first_name          0
last_name           0
gender              0
age                 0
marital_status      0
occupation          0
annual_income       0
city                0
state               0
customer_since      0
customer_segment    0
customer_tenure     0
dtype: int64

Duplicate Rows
0

Duplicate Primary Keys
0

Data Types
customer_id           str
first_name            str
last_name             str
gender                str
age                 int64
marital_status        str
occupation            str
annual_income       int64
city                  str
state                 str
customer_since        str
customer_segment      str
customer_tenure     int64
dtype: object


============================================================
ACCOUNTS DATASET
============================================================
Rows: 85000
Columns: 7

Missing Values
account_id        0
customer_id       0
account_type      0
balance           0
branch_id         0
account_status    0
open_date         0
dtype: int64

Duplicate Rows
0

Duplicate Primary Keys
0

Data Types
account_id            str
customer_id           str
account_type          str
balance           float64
branch_id             str
account_status        str
open_date             str
dtype: object


============================================================
LOANS DATASET
============================================================
Rows: 30000
Columns: 10

Missing Values
loan_id              0
customer_id          0
loan_type            0
loan_amount          0
interest_rate        0
emi                  0
credit_score         0
loan_status          0
default_flag         0
remaining_balance    0
dtype: int64

Duplicate Rows
0

Duplicate Primary Keys
0

Data Types
loan_id                  str
customer_id              str
loan_type                str
loan_amount            int64
interest_rate        float64
emi                    int64
credit_score           int64
loan_status              str
default_flag             str
remaining_balance      int64
dtype: object


============================================================
TRANSACTIONS DATASET
============================================================
Rows: 500000
Columns: 9

Missing Values
transaction_id      0
customer_id         0
account_id          0
date                0
transaction_type    0
amount              0
merchant            0
payment_mode        0
status              0
dtype: int64

Duplicate Rows
0

Duplicate Primary Keys
0

Data Types
transaction_id        str
customer_id           str
account_id            str
date                  str
transaction_type      str
amount              int64
merchant              str
payment_mode          str
status                str
dtype: object


============================================================
BRANCHES DATASET
============================================================
Rows: 100
Columns: 6

Missing Values
branch_id      0
branch_name    0
city           0
state          0
region         0
employees      0
dtype: int64

Duplicate Rows
0

Duplicate Primary Keys
0

Data Types
branch_id        str
branch_name      str
city             str
state            str
region           str
employees      int64
dtype: object

In [22]:
invalid_customers = accounts[
    ~accounts["customer_id"].isin(customers["customer_id"])
]

print("Invalid Customer IDs:", len(invalid_customers))

Invalid Customer IDs: 0

In [23]:
invalid_branches = accounts[
    ~accounts["branch_id"].isin(branches["branch_id"])
]

print("Invalid Branch IDs:", len(invalid_branches))

Invalid Branch IDs: 0

In [24]:
invalid_loans = loans[
    ~loans["customer_id"].isin(customers["customer_id"])
]

print("Invalid Loan Customers:", len(invalid_loans))

Invalid Loan Customers: 0

In [25]:
invalid_transactions = transactions[
    ~transactions["customer_id"].isin(customers["customer_id"])
]

print("Invalid Transaction Customers:", len(invalid_transactions))

Invalid Transaction Customers: 0

In [26]:
invalid_accounts = transactions[
    ~transactions["account_id"].isin(accounts["account_id"])
]

print("Invalid Transaction Accounts:", len(invalid_accounts))

Invalid Transaction Accounts: 0

In [27]:
customers.query("age < 18 or age > 100")

Empty DataFrame
Columns: [customer_id, first_name, last_name, gender, age, marital_status, occupation, annual_income, city, state, customer_since, customer_segment, customer_tenure]
Index: []

In [28]:
customers.query("annual_income <= 0")

Empty DataFrame
Columns: [customer_id, first_name, last_name, gender, age, marital_status, occupation, annual_income, city, state, customer_since, customer_segment, customer_tenure]
Index: []

In [29]:
accounts[
    (accounts["balance"] < 0) &
    (accounts["account_type"].isin(["Savings", "Checking"]))
]

Empty DataFrame
Columns: [account_id, customer_id, account_type, balance, branch_id, account_status, open_date]
Index: []

In [30]:
loans.query("credit_score < 300 or credit_score > 850")

Empty DataFrame
Columns: [loan_id, customer_id, loan_type, loan_amount, interest_rate, emi, credit_score, loan_status, default_flag, remaining_balance]
Index: []

In [31]:
loans[loans["remaining_balance"] > loans["loan_amount"]]

Empty DataFrame
Columns: [loan_id, customer_id, loan_type, loan_amount, interest_rate, emi, credit_score, loan_status, default_flag, remaining_balance]
Index: []

In [32]:
loans[
    (loans["loan_status"] == "Closed") &(loans["remaining_balance"] != 0)]

Empty DataFrame
Columns: [loan_id, customer_id, loan_type, loan_amount, interest_rate, emi, credit_score, loan_status, default_flag, remaining_balance]
Index: []

In [33]:
transactions.query("amount <= 0")
transactions["transaction_type"].value_counts()
transactions["payment_mode"].value_counts()

payment_mode
UPI              249859
Debit Card       100511
Credit Card       74963
Bank Transfer     49876
Net Banking       24791
Name: count, dtype: int64